source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HostsFileUpdater_Example', :exclusive => true do
  pod "HostsFileUpdater", :path => "../"
end

target 'HostsFileUpdater_Tests', :exclusive => true do
  pod "HostsFileUpdater", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
